name: Hello World Workflow

# Triggers the workflow on any push event to the repository
on:
  pull_request:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello, world!"


# linting

  lint_my_code:
    runs-on: ubuntu-latest

    steps:
      - name: lint the code in my repo
        run: next lint
# testing
# auditing